import type { Metadata } from "next";
import { Bell, Camera, ChevronRight, LockKeyhole, Mail, ShieldCheck, Users } from "lucide-react";
import { PageHeader, Pill } from "@/components/ui";

export const metadata: Metadata = { title: "Space settings" };
export default function SettingsPage() { return <div className="mx-auto max-w-5xl px-4 py-6 sm:px-7 sm:py-9 xl:px-10"><PageHeader eyebrow="Space settings" title="Our table, our rules." description="Manage the people, privacy, and preferences for this shared dinner journal." />
  <div className="mt-8 grid gap-6 lg:grid-cols-[210px_1fr]"><nav className="space-y-1">{["General", "Members", "Privacy", "Notifications"].map((item, index) => <button key={item} className={`focus-ring w-full rounded-lg px-4 py-2.5 text-left text-sm font-semibold ${index === 0 ? "bg-white/70 text-[var(--wine)] shadow-sm" : "text-[var(--muted)] hover:bg-white/45"}`}>{item}</button>)}</nav><div className="space-y-5"><section className="rounded-2xl border hairline bg-white/55 p-5 sm:p-7"><h2 className="font-editorial text-2xl">Space details</h2><div className="mt-6 grid gap-5 sm:grid-cols-[auto_1fr]"><button className="focus-ring grid size-20 place-items-center rounded-2xl bg-[var(--wine)] text-white"><Camera size={22} /><span className="sr-only">Change space photo</span></button><div className="grid gap-4"><label><span className="text-sm font-bold">Space name</span><input defaultValue="Our table" className="field-input mt-2" /></label><label><span className="text-sm font-bold">Tagline</span><input defaultValue="The dinners we want to remember" className="field-input mt-2" /></label></div></div><div className="mt-6 flex justify-end"><button className="focus-ring rounded-full bg-[var(--wine)] px-5 py-2.5 text-sm font-bold text-white">Save changes</button></div></section>
    <section className="rounded-2xl border hairline bg-white/55 p-5 sm:p-7"><div className="flex items-center justify-between"><div><h2 className="font-editorial text-2xl">Members</h2><p className="mt-1 text-sm text-[var(--muted)]">Everyone here can add and edit dinners.</p></div><button className="focus-ring inline-flex items-center gap-2 rounded-full border hairline px-4 py-2 text-sm font-bold text-[var(--wine)]"><Mail size={15} /> Invite</button></div><div className="mt-5 divide-y hairline">{[["Alicia", "alicia@example.com", "Owner"], ["Maya", "maya@example.com", "Member"], ["Theo", "theo@example.com", "Member"]].map(([name,email,role], index) => <div key={name} className="flex items-center gap-3 py-4"><span className="grid size-10 place-items-center rounded-full bg-[#d8b69b] text-sm font-bold">{name[0]}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold">{name}</p><p className="truncate text-xs text-[var(--muted)]">{email}</p></div><Pill tone={index === 0 ? "wine" : "neutral"}>{role}</Pill><ChevronRight size={16} className="text-[var(--muted)]" /></div>)}</div></section>
    <section className="rounded-2xl bg-[#efe3d2] p-5 sm:p-7"><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-white/70"><ShieldCheck size={20} className="text-[var(--olive)]" /></span><div><h2 className="font-editorial text-2xl">Private by default</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Only members of this space can read or change dinners, notes, ratings, and photos. Share links are view-only and can be revoked at any time.</p><div className="mt-4 flex flex-wrap gap-3 text-xs font-semibold text-[var(--muted)]"><span className="inline-flex items-center gap-1"><LockKeyhole size={14} /> Member-only data</span><span className="inline-flex items-center gap-1"><Users size={14} /> 3 members</span><span className="inline-flex items-center gap-1"><Bell size={14} /> Quiet notifications</span></div></div></div></section></div></div>
  </div>; }
