"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, CalendarDays, Camera, Check, Copy, Edit3, MapPin, MessageCircle, Plus, Trash2, Utensils, Wine, X } from "lucide-react";
import clsx from "clsx";
import { AvatarStack, Pill } from "@/components/ui";
import { VoiceNoteButton } from "@/components/voice-note-button";
import { useAppData } from "@/components/app-data-provider";
import { formatDinnerDateTime } from "@/lib/date-format";

type Dialog = "edit" | "course" | "course-edit" | "pair" | "wine" | "note" | null;

export function DinnerDetail({ dinnerId }: { dinnerId: string }) {
  const data = useAppData(); const dinner = data.dinners.find((item) => item.id === dinnerId); const [tab, setTab] = useState<"plan" | "table" | "wines" | "memory">("table"); const [dialog, setDialog] = useState<Dialog>(null); const [selectedCourseId, setSelectedCourseId] = useState(""); const [copied, setCopied] = useState(false); const [busy, setBusy] = useState(false); const [uploadingPhotos, setUploadingPhotos] = useState(false); const [deletingPhotoId, setDeletingPhotoId] = useState(""); const [photoStatus, setPhotoStatus] = useState(""); const [message, setMessage] = useState(""); const fileInput = useRef<HTMLInputElement>(null);
  if (!data.ready) return <div className="grid min-h-[60vh] place-items-center text-sm text-[var(--muted)]">Setting the table…</div>;
  if (!dinner) return <div className="mx-auto max-w-xl px-5 py-20 text-center"><h1 className="font-editorial text-4xl">Dinner not found.</h1><Link href="/journal" className="mt-5 inline-block font-semibold text-[var(--wine)]">Return to the journal</Link></div>;
  const dinnerExperiences = dinner.wineExperienceIds.map((id) => data.wineExperiences.find((item) => item.id === id)).filter((item): item is NonNullable<typeof item> => Boolean(item));

  const copyLink = async () => { setBusy(true); try { const link = await data.createShareLink(dinner.id); await navigator.clipboard.writeText(link); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch (cause) { setMessage(errorText(cause)); } finally { setBusy(false); } };
  const submitDialog = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); try {
    if (dialog === "edit") await data.updateDinner(dinner.id, { title: String(form.get("title")), date: String(form.get("date")), locationType: String(form.get("locationType")) as typeof dinner.locationType, venue: String(form.get("venue")), guests: String(form.get("guests") ?? "").split(",").map((name) => name.trim()).filter(Boolean), summary: String(form.get("summary")), status: String(form.get("status")) as typeof dinner.status });
    if (dialog === "course") await data.addCourse(dinner.id, String(form.get("title")), String(form.get("description")));
    if (dialog === "course-edit") await data.updateCourse(dinner.id, selectedCourseId, String(form.get("title")), String(form.get("description")));
    if (dialog === "note") await data.addNote(dinner.id, String(form.get("body")));
    if (dialog === "wine") await data.openWine(dinner.id, String(form.get("wineId")), String(form.get("servingNote")));
    if (dialog === "pair") { const wineId = String(form.get("wineId")); const experienceId = await data.openWine(dinner.id, wineId, String(form.get("servingNote"))); await data.pairWine(dinner.id, String(form.get("courseId")), experienceId, String(form.get("pairingNote"))); }
    setDialog(null);
  } catch (cause) { setMessage(errorText(cause)); } finally { setBusy(false); } };
  const uploadPhotos = async (event: React.ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []); if (!files.length) return; setUploadingPhotos(true); setPhotoStatus(""); setMessage(""); try { await data.addPhotos(dinner.id, files); setPhotoStatus(`${files.length} ${files.length === 1 ? "photo" : "photos"} added to this memory.`); setTab("memory"); } catch (cause) { setMessage(errorText(cause)); } finally { setUploadingPhotos(false); event.target.value = ""; } };
  const deletePhoto = async (photoId: string) => { if (!window.confirm("Delete this photo from the dinner memory?")) return; setDeletingPhotoId(photoId); setPhotoStatus(""); setMessage(""); try { await data.deletePhoto(dinner.id, photoId); setPhotoStatus("Photo deleted."); } catch (cause) { setMessage(errorText(cause)); } finally { setDeletingPhotoId(""); } };

  return <div className="mx-auto max-w-[1400px] px-4 py-5 sm:px-7 sm:py-8 xl:px-10">
    <header><div className="flex items-center justify-between"><Link href="/journal" className="focus-ring inline-flex items-center gap-2 rounded-lg text-sm font-semibold text-[var(--muted)]"><ArrowLeft size={17} /> Journal</Link><div className="flex gap-2"><button disabled={busy} onClick={copyLink} className="focus-ring inline-flex items-center gap-2 rounded-full border hairline bg-white/55 px-3 py-2 text-sm font-semibold disabled:opacity-50">{copied ? <Check size={16} /> : <Copy size={16} />}<span className="hidden sm:inline">{copied ? "Copied" : "Share"}</span></button><button onClick={() => setDialog("edit")} className="focus-ring inline-flex items-center gap-2 rounded-full bg-[var(--wine)] px-4 py-2 text-sm font-semibold text-white"><Edit3 size={15} /> Edit</button></div></div>
      <div className="mt-7 grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex flex-wrap items-center gap-2"><Pill tone={dinner.status === "remembered" ? "olive" : "wine"}>{dinner.status}</Pill><time dateTime={dinner.date} className="text-sm text-[var(--muted)]">{formatDinnerDateTime(dinner.date, "long")}</time></div><h1 className="font-editorial mt-3 max-w-4xl text-5xl leading-[.95] sm:text-6xl">{dinner.title}</h1><div className="mt-5 flex flex-wrap items-center gap-5 text-sm text-[var(--muted)]"><span className="inline-flex items-center gap-2"><MapPin size={16} />{dinner.venue}</span><AvatarStack names={dinner.guests} /></div></div><VoiceNoteButton onSave={(blob, seconds) => data.addVoiceNote(dinner.id, blob, seconds)} /></div>
    </header>
    {message && <p role="alert" className="mt-5 rounded-xl bg-[#f4d9d2] px-4 py-3 text-sm font-semibold text-[var(--wine)]">{message}</p>}
    {photoStatus && <p role="status" className="mt-5 rounded-xl bg-[#e5ead8] px-4 py-3 text-sm font-semibold text-[#48502f]">{photoStatus}</p>}
    <div className="mt-8 flex overflow-x-auto border-b hairline" role="tablist">{(["plan", "table", "wines", "memory"] as const).map((item) => <button key={item} role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={clsx("focus-ring -mb-px shrink-0 border-b-2 px-4 py-3 text-sm font-bold capitalize", tab === item ? "border-[var(--wine)] text-[var(--wine)]" : "border-transparent text-[var(--muted)]")}>{item === "table" ? "At the table" : item}</button>)}</div>

    {tab === "plan" && <div className="mt-7 grid gap-4 md:grid-cols-3"><SummaryCard icon={Utensils} label="Menu" value={`${dinner.courses.length} ${dinner.courses.length === 1 ? "course" : "courses"}`} detail="Flexible until the last plate" /><SummaryCard icon={Wine} label="Wine" value={`${dinner.wineExperienceIds.length} ${dinner.wineExperienceIds.length === 1 ? "bottle" : "bottles"}`} detail="Paired course by course" /><SummaryCard icon={Camera} label="Memories" value={`${dinner.photoCount} ${dinner.photoCount === 1 ? "photo" : "photos"}`} detail={`${dinner.voiceNotes?.length ?? 0} ${(dinner.voiceNotes?.length ?? 0) === 1 ? "voice note" : "voice notes"}`} /></div>}
    {tab === "memory" && <div className="mt-7 max-w-4xl space-y-5"><div className="rounded-2xl border hairline bg-white/55 p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--tomato)]">The lasting note</p><blockquote className="font-editorial mt-4 text-3xl leading-tight">“{dinner.summary || "Add the detail you never want to forget."}”</blockquote><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => setDialog("edit")} className="focus-ring rounded-full bg-[var(--wine)] px-4 py-2 text-sm font-bold text-white">Edit memory</button><span className="self-center text-sm text-[var(--muted)]">{dinner.photoCount} photos · {dinner.notes?.length ?? 0} notes</span></div></div>{Boolean(dinner.photos?.length) && <section className="grid grid-cols-2 gap-3 sm:grid-cols-3">{dinner.photos?.map((photo) => <figure key={photo.id} className="group relative overflow-hidden rounded-xl bg-black/5"><Image src={photo.url} alt={photo.caption || "Dinner memory"} width={640} height={480} unoptimized className="aspect-[4/3] h-auto w-full object-cover" /><button type="button" disabled={deletingPhotoId === photo.id} onClick={() => void deletePhoto(photo.id)} aria-label={`Delete ${photo.caption || "photo"}`} className="focus-ring absolute right-2 top-2 grid size-9 place-items-center rounded-full bg-black/65 text-white shadow-lg backdrop-blur hover:bg-[var(--wine)] disabled:cursor-wait disabled:opacity-60"><Trash2 size={16} /></button></figure>)}</section>}{Boolean(dinner.voiceNotes?.length) && <section className="rounded-2xl border hairline bg-white/55 p-5"><h2 className="font-editorial text-2xl">Voice notes</h2><div className="mt-4 space-y-3">{dinner.voiceNotes?.map((note, index) => <div key={note.id} className="flex items-center gap-3"><span className="text-sm font-semibold">Note {index + 1} · {note.durationSeconds}s</span>{note.url && <audio controls src={note.url} className="h-9 max-w-full flex-1" />}</div>)}</div></section>}</div>}
    {tab === "wines" && <section className="mt-7 max-w-5xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--tomato)]">Wine list</p><h2 className="font-editorial mt-1 text-3xl">Bottles opened at this dinner</h2><p className="mt-2 text-sm text-[var(--muted)]">Keep every bottle here, whether or not it was paired with a course.</p></div><button onClick={() => setDialog("wine")} className="focus-ring inline-flex items-center gap-2 rounded-full bg-[var(--wine)] px-4 py-2.5 text-sm font-bold text-white"><Plus size={16} /> Add a bottle</button></div>
      {dinnerExperiences.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2">{dinnerExperiences.map((experience) => { const wine = data.wines.find((item) => item.id === experience.wineId); if (!wine) return null; const pairedCourses = dinner.pairings.filter((pairing) => pairing.wineExperienceId === experience.id).map((pairing) => dinner.courses.find((course) => course.id === pairing.courseId)?.title).filter(Boolean); return <Link key={experience.id} href={`/wines/${wine.id}`} className="lift focus-ring overflow-hidden rounded-2xl border hairline bg-white/55"><div className="grid min-h-52 grid-cols-[110px_1fr] sm:grid-cols-[140px_1fr]"><div className="grid place-items-center overflow-hidden bg-[#e9dbc8]">{wine.imageUrl ? <Image src={wine.imageUrl} alt={`${wine.producer} label`} width={280} height={360} unoptimized className="h-full w-full object-cover" /> : <Wine size={48} strokeWidth={1} className="text-[var(--wine)]" />}</div><div className="flex min-w-0 flex-col p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--tomato)]">{wine.region} · {wine.vintage}</p><h3 className="font-editorial mt-2 text-2xl leading-tight">{wine.producer}</h3><p className="mt-1 text-sm text-[var(--muted)]">{wine.cuvee}</p><p className="mt-4 inline-flex items-center gap-1.5 text-xs font-semibold text-[var(--muted)]"><CalendarDays size={14} /> {formatDinnerDateTime(dinner.date)}</p>{experience.servingNote && <p className="mt-3 text-sm italic leading-5 text-[var(--muted)]">“{experience.servingNote}”</p>}{pairedCourses.length > 0 && <p className="mt-auto pt-4 text-xs font-semibold text-[var(--olive)]">Paired with {pairedCourses.join(", ")}</p>}</div></div></Link>; })}</div> : <div className="mt-6 rounded-2xl border border-dashed hairline bg-white/35 p-10 text-center"><Wine size={32} className="mx-auto text-[var(--wine)]" /><h3 className="font-editorial mt-3 text-2xl">No bottles yet</h3><p className="mt-2 text-sm text-[var(--muted)]">Add the first bottle to this dinner&apos;s wine list.</p><button onClick={() => setDialog("wine")} className="focus-ring mt-5 rounded-full border hairline bg-white/70 px-4 py-2 text-sm font-bold text-[var(--wine)]">Add a bottle</button></div>}
    </section>}
    {tab === "table" && <div className="mt-7 grid gap-7 xl:grid-cols-[minmax(0,1fr)_330px]"><div className="space-y-4">{dinner.courses.map((course, index) => { const pairing = dinner.pairings.find((item) => item.courseId === course.id); const experience = pairing && data.wineExperiences.find((item) => item.id === pairing.wineExperienceId); const wine = experience && data.wines.find((item) => item.id === experience.wineId); const ownRating = pairing && dinner.ratings.find((item) => item.targetId === pairing.id && (item.personId === data.viewer.id || (!item.personId && item.personName === data.viewer.name))); return <article key={course.id} className="rounded-2xl border hairline bg-white/55 p-5 sm:p-6"><div className="flex gap-4"><span className="font-editorial text-3xl text-[#b7a093]">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h2 className="font-editorial text-2xl sm:text-3xl">{course.title}</h2><p className="mt-1 text-sm text-[var(--muted)]">{course.description}</p></div><button type="button" onClick={() => { setSelectedCourseId(course.id); setDialog("course-edit"); }} className="focus-ring shrink-0 rounded-full px-3 py-1.5 text-xs font-bold text-[var(--muted)] hover:bg-black/5">Edit course</button></div>
      {wine && pairing ? <div className="mt-5 rounded-xl bg-[#efe4d4] p-4"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[var(--wine)] text-white"><Wine size={17} /></span><div className="min-w-0 flex-1"><Link href={`/wines/${wine.id}`} className="font-bold text-[var(--wine)] hover:underline">{wine.producer} · {wine.vintage}</Link><p className="text-sm text-[var(--muted)]">{wine.cuvee}</p>{pairing.note && <p className="mt-3 border-l-2 border-[var(--tomato)] pl-3 text-sm italic leading-6">“{pairing.note}”</p>}</div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t hairline pt-4"><span className="text-xs font-bold uppercase tracking-[.14em] text-[var(--muted)]">Your pairing rating</span><div className="flex gap-1">{[1,2,3,4,5].map((value) => <button key={value} type="button" onClick={() => void data.ratePairing(dinner.id, pairing.id, value)} aria-label={`${value} out of 5`} className={clsx("focus-ring grid size-8 place-items-center rounded-full border text-xs font-bold", value <= (ownRating?.rating ?? 0) ? "border-[var(--wine)] bg-[var(--wine)] text-white" : "hairline bg-white/60 text-[var(--muted)]")}>{value}</button>)}</div></div></div> : <button onClick={() => { setSelectedCourseId(course.id); setDialog("pair"); }} className="focus-ring mt-5 inline-flex items-center gap-2 rounded-full border hairline px-4 py-2 text-sm font-bold text-[var(--wine)]"><Plus size={16} /> Pair a wine</button>}
      </div></div></article>; })}<button onClick={() => setDialog("course")} className="focus-ring flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-[#bba99d] py-4 text-sm font-bold text-[var(--wine)]"><Plus size={17} /> Add another course</button></div>
      <aside className="space-y-4"><div className="rounded-2xl bg-[var(--wine-deep)] p-5 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e8a78f]">Quick capture</p><h2 className="font-editorial mt-2 text-3xl">Don&apos;t lose the moment.</h2><div className="mt-5 grid grid-cols-2 gap-2"><button disabled={uploadingPhotos} onClick={() => fileInput.current?.click()} className="focus-ring flex flex-col items-center gap-2 rounded-xl bg-white/10 p-4 text-sm font-semibold hover:bg-white/15 disabled:cursor-wait disabled:opacity-60"><Camera size={20} /> {uploadingPhotos ? "Uploading…" : "Add photos"}</button><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" multiple className="hidden" onChange={uploadPhotos} /><button onClick={() => setDialog("note")} className="focus-ring flex flex-col items-center gap-2 rounded-xl bg-white/10 p-4 text-sm font-semibold hover:bg-white/15"><MessageCircle size={20} /> Add note</button></div><div className="mt-3"><VoiceNoteButton onSave={(blob, seconds) => data.addVoiceNote(dinner.id, blob, seconds)} /></div></div>
        <div className="rounded-2xl border hairline bg-white/50 p-5"><div className="flex items-center justify-between"><h3 className="font-editorial text-2xl">Around the table</h3><span className="text-xs text-[var(--muted)]">{dinner.ratings.length + (dinner.notes?.length ?? 0)} notes</span></div><div className="mt-5 space-y-5">{[...(dinner.notes ?? []).map((note) => ({ id: note.id, personName: note.authorName, text: note.body, rating: null as number | null })), ...dinner.ratings.map((rating) => ({ id: rating.id, personName: rating.personName, text: rating.note, rating: rating.rating as number | null }))].map((item) => <div key={item.id} className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#d7c0a7] text-xs font-bold">{item.personName[0]}</span><div><p className="text-sm"><strong>{item.personName}</strong>{item.rating && <> rated it <strong>{item.rating}/5</strong></>}</p>{item.text && <p className="mt-1 text-sm leading-5 text-[var(--muted)]">{item.text}</p>}</div></div>)}</div></div>
      </aside></div>}

    {dialog && <div className="fixed inset-0 z-50 grid place-items-end bg-black/45 sm:place-items-center sm:p-5"><form onSubmit={submitDialog} role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-lg overflow-auto rounded-t-3xl bg-[var(--paper)] p-6 sm:rounded-3xl"><div className="flex items-center justify-between"><h2 className="font-editorial text-3xl">{dialogTitle(dialog)}</h2><button type="button" onClick={() => setDialog(null)} aria-label="Close" className="focus-ring rounded-full p-2"><X size={19} /></button></div><DialogFields dialog={dialog} dinner={dinner} wines={data.wines} selectedCourseId={selectedCourseId} />{message && <p role="alert" className="mt-4 text-sm text-[var(--tomato)]">{message}</p>}<button disabled={busy} className="focus-ring mt-6 w-full rounded-full bg-[var(--wine)] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{busy ? "Saving…" : "Save"}</button></form></div>}
  </div>;
}

function DialogFields({ dialog, dinner, wines, selectedCourseId }: { dialog: Exclude<Dialog, null>; dinner: ReturnType<typeof useAppData>["dinners"][number]; wines: ReturnType<typeof useAppData>["wines"]; selectedCourseId: string }) {
  if (dialog === "edit") return <div className="mt-6 grid gap-4"><label><span className="text-sm font-bold">Title</span><input name="title" required defaultValue={dinner.title} className="field-input mt-2" /></label><label><span className="text-sm font-bold">When</span><input name="date" type="datetime-local" defaultValue={toDatetimeLocal(dinner.date)} className="field-input mt-2" /></label><label><span className="text-sm font-bold">Location type</span><select name="locationType" defaultValue={dinner.locationType} className="field-input mt-2"><option value="home">At home</option><option value="restaurant">Restaurant</option></select></label><label><span className="text-sm font-bold">Venue</span><input name="venue" defaultValue={dinner.venue} className="field-input mt-2" /></label><label><span className="text-sm font-bold">Guests</span><input name="guests" defaultValue={dinner.guests.join(", ")} className="field-input mt-2" /></label><label><span className="text-sm font-bold">Status</span><select name="status" defaultValue={dinner.status} className="field-input mt-2"><option value="planning">Planning</option><option value="happening">Happening</option><option value="remembered">Remembered</option></select></label><label><span className="text-sm font-bold">Lasting note</span><textarea name="summary" defaultValue={dinner.summary} rows={4} className="field-input mt-2" /></label></div>;
  if (dialog === "course") return <div className="mt-6 grid gap-4"><label><span className="text-sm font-bold">Course name</span><input name="title" required autoFocus className="field-input mt-2" /></label><label><span className="text-sm font-bold">Details</span><textarea name="description" rows={3} className="field-input mt-2" /></label></div>;
  if (dialog === "course-edit") { const course = dinner.courses.find((item) => item.id === selectedCourseId); return <div className="mt-6 grid gap-4"><label><span className="text-sm font-bold">Course name</span><input name="title" required autoFocus defaultValue={course?.title} className="field-input mt-2" /></label><label><span className="text-sm font-bold">Details</span><textarea name="description" rows={3} defaultValue={course?.description} className="field-input mt-2" /></label></div>; }
  if (dialog === "note") return <label className="mt-6 block"><span className="text-sm font-bold">What do you want to remember?</span><textarea name="body" required autoFocus rows={5} className="field-input mt-2" /></label>;
  if (dialog === "wine") return <div className="mt-6 grid gap-4"><label><span className="text-sm font-bold">Wine</span><select name="wineId" required className="field-input mt-2">{wines.map((wine) => <option key={wine.id} value={wine.id}>{wine.producer} · {wine.cuvee} · {wine.vintage}</option>)}</select></label><label><span className="text-sm font-bold">Serving note</span><input name="servingNote" className="field-input mt-2" placeholder="Decanted 45 minutes" /></label></div>;
  return <div className="mt-6 grid gap-4"><label><span className="text-sm font-bold">Course</span><select name="courseId" required defaultValue={selectedCourseId || dinner.courses[0]?.id} className="field-input mt-2">{dinner.courses.map((course) => <option key={course.id} value={course.id}>{course.title}</option>)}</select></label><label><span className="text-sm font-bold">Wine</span><select name="wineId" required className="field-input mt-2">{wines.map((wine) => <option key={wine.id} value={wine.id}>{wine.producer} · {wine.cuvee} · {wine.vintage}</option>)}</select></label><label><span className="text-sm font-bold">Serving note</span><input name="servingNote" className="field-input mt-2" placeholder="Decanted 45 minutes" /></label><label><span className="text-sm font-bold">Why it works</span><textarea name="pairingNote" rows={3} className="field-input mt-2" /></label></div>;
}
function SummaryCard({ icon: Icon, label, value, detail }: { icon: typeof Utensils; label: string; value: string; detail: string }) { return <div className="rounded-2xl border hairline bg-white/55 p-5"><Icon size={20} className="text-[var(--tomato)]" /><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-[var(--muted)]">{label}</p><p className="font-editorial mt-1 text-2xl">{value}</p><p className="mt-1 text-sm text-[var(--muted)]">{detail}</p></div>; }
function dialogTitle(dialog: Exclude<Dialog, null>) { return { edit: "Edit dinner", course: "Add a course", "course-edit": "Edit course", pair: "Pair a wine", wine: "Add a bottle", note: "Add a note" }[dialog]; }
function errorText(cause: unknown) { return cause instanceof Error ? cause.message : "Something went wrong. Please try again."; }
function toDatetimeLocal(value: string) { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
