"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Users } from "lucide-react";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/client";
import { GoogleSignIn } from "@/components/google-sign-in";

export function InviteView({ token }: { token: string }) {
  const router = useRouter(); const [activeEmail, setActiveEmail] = useState<string | null | undefined>(undefined); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); const [insideWeChat, setInsideWeChat] = useState(false); const live = isSupabaseConfigured();
  useEffect(() => { let current = true; window.queueMicrotask(() => { if (current) setInsideWeChat(/MicroMessenger/i.test(window.navigator.userAgent)); }); if (!live) { window.queueMicrotask(() => { if (current) setActiveEmail(null); }); return () => { current = false; }; } void createClient().auth.getUser().then(({ data }) => { if (current) setActiveEmail(data.user?.email ?? null); }); return () => { current = false; }; }, [live]);
  const accept = async () => { if (!live) { setMessage("Invitation accepted in demo mode."); window.setTimeout(() => router.push("/"), 700); return; } setPending(true); setMessage(""); const { error } = await createClient().rpc("accept_space_invitation", { raw_token: token }); if (error) { if (/invited email address/i.test(error.message)) setMessage(`This invitation was sent to a different Google account. You’re signed in as ${activeEmail ?? "another account"}. Switch accounts to continue.`); else if (/invalid or expired/i.test(error.message)) setMessage("This invitation expired or was replaced. Ask the space owner for a new link."); else setMessage(error.message); setPending(false); } else { router.replace("/"); router.refresh(); } };
  const switchAccount = async () => { setPending(true); setMessage(""); const { error } = await createClient().auth.signOut({ scope: "local" }); if (error) setMessage(error.message); else setActiveEmail(null); setPending(false); };
  return <main className="paper-grain grid min-h-screen place-items-center bg-[var(--wine-deep)] px-5 py-8 text-white"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[.07] p-7 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-white/10"><Users /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-[#e4a38d]">Invitation</p><h1 className="font-editorial mt-2 text-4xl">Join the table.</h1><p className="mt-3 text-sm leading-6 text-white/65">You’ve been invited to share dinners, wine notes, ratings, and memories.</p>{insideWeChat && <p className="mt-5 rounded-xl bg-[#f6ddbb] px-4 py-3 text-left text-xs font-semibold leading-5 text-[#5c2730]">Google sign-in may be blocked inside WeChat. Tap ••• and open this link in Safari or Chrome.</p>}<div className="mt-7">{live && activeEmail === undefined ? <button disabled className="w-full rounded-full bg-white/80 px-5 py-3 text-sm font-bold text-[var(--wine)] opacity-70">Checking account…</button> : live && !activeEmail ? <GoogleSignIn nextPath={`/invite/${token}`} forceAccountChoice label="Sign in with invited Google account" /> : <><p className="mb-3 text-xs text-white/60">Signed in as <strong className="text-white">{activeEmail}</strong></p><button disabled={pending} onClick={accept} className="focus-ring w-full rounded-full bg-white px-5 py-3 text-sm font-bold text-[var(--wine)] disabled:opacity-60">{pending ? "Joining…" : "Accept invitation"}</button>{live && <button type="button" disabled={pending} onClick={switchAccount} className="focus-ring mt-3 w-full rounded-full border border-white/25 px-5 py-3 text-sm font-bold text-white disabled:opacity-60">Switch Google account</button>}</>}</div>{message && <p role="status" className="mt-4 rounded-xl bg-white/10 px-4 py-3 text-sm leading-5 text-white/80">{message}</p>}</div></main>;
}
