"use client";

import { useEffect, useState } from "react";
import { Camera, LockKeyhole, MapPin, Wine } from "lucide-react";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/client";
import type { Dinner } from "@/lib/types";

type SharedPayload = { title: string; venue_name: string; scheduled_at: string; summary: string; courses: { id: string; position: number; title: string; description: string }[]; wines: { producer: string; cuvee: string; vintage: number }[] };

export function SharedDinner({ token }: { token: string }) {
  const [dinner, setDinner] = useState<SharedPayload | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { const load = async () => { if (isSupabaseConfigured()) { const { data } = await createClient().rpc("get_shared_dinner", { raw_token: token }); setDinner(data as SharedPayload | null); } else { const stored = JSON.parse(window.localStorage.getItem("at-our-table-shares-v1") ?? "{}") as Record<string, Dinner>; const local = stored[token]; if (local) setDinner({ title: local.title, venue_name: local.venue, scheduled_at: local.date, summary: local.summary, courses: local.courses, wines: local.wineExperienceIds.map(() => ({ producer: "Wine from the table", cuvee: "", vintage: 0 })) }); } setLoading(false); }; void load(); }, [token]);
  if (loading) return <div className="grid min-h-screen place-items-center text-sm text-[var(--muted)]">Opening the shared memory…</div>;
  if (!dinner) return <main className="grid min-h-screen place-items-center px-5 text-center"><div><LockKeyhole className="mx-auto text-[var(--wine)]" /><h1 className="font-editorial mt-4 text-4xl">This link is no longer available.</h1><p className="mt-2 text-sm text-[var(--muted)]">It may have expired or been revoked.</p></div></main>;
  return <main className="paper-grain min-h-screen bg-[var(--paper)]"><header className="border-b hairline px-5 py-4"><div className="mx-auto flex max-w-4xl items-center justify-between"><span className="font-editorial text-xl text-[var(--wine)]">At Our Table</span><span className="inline-flex items-center gap-1.5 text-xs font-semibold text-[var(--muted)]"><LockKeyhole size={13} /> Read-only memory</span></div></header><article className="mx-auto max-w-4xl px-5 py-10 sm:py-16"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--tomato)]">Shared from our table</p><h1 className="font-editorial mt-3 text-5xl leading-[.95] sm:text-6xl">{dinner.title}</h1><div className="mt-5 flex flex-wrap gap-5 text-sm text-[var(--muted)]"><span className="inline-flex items-center gap-2"><MapPin size={16} />{dinner.venue_name}</span><span className="inline-flex items-center gap-2"><Camera size={16} />Private photos hidden</span><span className="inline-flex items-center gap-2"><Wine size={16} />{dinner.wines.length} wines</span></div><blockquote className="font-editorial mt-10 border-l-2 border-[var(--tomato)] pl-6 text-3xl leading-tight">“{dinner.summary || "A dinner worth remembering."}”</blockquote><section className="mt-10 space-y-3">{dinner.courses.map((course, index) => <div key={course.id} className="flex gap-4 rounded-xl border hairline bg-white/45 p-4"><span className="font-editorial text-2xl text-[#ac988d]">{index + 1}</span><div><h2 className="font-editorial text-xl">{course.title}</h2><p className="mt-1 text-sm text-[var(--muted)]">{course.description}</p></div></div>)}</section><p className="mt-12 text-center text-xs text-[var(--muted)]">This private link can be revoked by the space owner.</p></article></main>;
}
