"use client";

import { useEffect, useRef, useState } from "react";
import { Bell, Copy, LockKeyhole, Mail, ShieldCheck, Users, X } from "lucide-react";
import { useAppData } from "@/components/app-data-provider";
import { PageHeader, Pill } from "@/components/ui";

type Tab = "General" | "Members" | "Privacy" | "Notifications";
const NOTIFICATION_KEY = "at-our-table-notifications-v1";

export function SpaceSettings() {
  const { space, mode, updateSpace, inviteMember } = useAppData(); const [tab, setTab] = useState<Tab>("General"); const [inviteOpen, setInviteOpen] = useState(false); const [message, setMessage] = useState(""); const [inviteLink, setInviteLink] = useState(""); const [copyState, setCopyState] = useState<"idle" | "copying" | "copied" | "failed">("idle"); const [pending, setPending] = useState(false); const [shareAlerts, setShareAlerts] = useState(true); const [dinnerReminders, setDinnerReminders] = useState(true); const [preferencesReady, setPreferencesReady] = useState(false); const inviteLinkInput = useRef<HTMLInputElement>(null);
  useEffect(() => { try { const saved = JSON.parse(window.localStorage.getItem(NOTIFICATION_KEY) ?? "null") as { shareAlerts?: boolean; dinnerReminders?: boolean } | null; if (saved) { setShareAlerts(saved.shareAlerts ?? true); setDinnerReminders(saved.dinnerReminders ?? true); } } finally { setPreferencesReady(true); } }, []);
  useEffect(() => { if (preferencesReady) window.localStorage.setItem(NOTIFICATION_KEY, JSON.stringify({ shareAlerts, dinnerReminders })); }, [preferencesReady, shareAlerts, dinnerReminders]);
  const saveSpace = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); const form = new FormData(event.currentTarget); try { await updateSpace(String(form.get("name")), String(form.get("tagline"))); setMessage("Space details saved."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Could not save changes."); } finally { setPending(false); } };
  const sendInvite = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); try { const form = new FormData(event.currentTarget); const link = await inviteMember(String(form.get("email"))); setInviteLink(link); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Could not create invitation."); } finally { setPending(false); } };
  const copyInviteLink = async () => { setCopyState("copying"); try { if (!navigator.clipboard?.writeText) throw new Error("Clipboard unavailable"); await Promise.race([navigator.clipboard.writeText(inviteLink), new Promise<never>((_, reject) => window.setTimeout(() => reject(new Error("Clipboard timed out")), 2000))]); setCopyState("copied"); } catch { const input = inviteLinkInput.current; input?.focus(); input?.select(); setCopyState(input && document.execCommand("copy") ? "copied" : "failed"); } };
  return <div className="mx-auto max-w-5xl px-4 py-6 sm:px-7 sm:py-9 xl:px-10"><PageHeader eyebrow="Space settings" title="Our table, our rules." description={`Manage the people, privacy, and preferences for this ${mode === "live" ? "live" : "demo"} dinner journal.`} />
    <div className="mt-8 grid gap-6 lg:grid-cols-[210px_1fr]"><nav className="flex gap-1 overflow-x-auto lg:block lg:space-y-1">{(["General", "Members", "Privacy", "Notifications"] as Tab[]).map((item) => <button key={item} onClick={() => { setTab(item); setMessage(""); }} className={`focus-ring shrink-0 rounded-lg px-4 py-2.5 text-left text-sm font-semibold lg:w-full ${tab === item ? "bg-white/70 text-[var(--wine)] shadow-sm" : "text-[var(--muted)] hover:bg-white/45"}`}>{item}</button>)}</nav><div>
      {message && <p role="status" className="mb-4 rounded-xl bg-[#e5ead8] px-4 py-3 text-sm font-semibold text-[#48502f]">{message}</p>}
      {tab === "General" && <form onSubmit={saveSpace} className="rounded-2xl border hairline bg-white/55 p-5 sm:p-7"><h2 className="font-editorial text-2xl">Space details</h2><div className="mt-6 grid gap-4"><label><span className="text-sm font-bold">Space name</span><input name="name" defaultValue={space.name} className="field-input mt-2" /></label><label><span className="text-sm font-bold">Tagline</span><input name="tagline" defaultValue={space.tagline} className="field-input mt-2" /></label></div><div className="mt-6 flex justify-end"><button disabled={pending} className="focus-ring rounded-full bg-[var(--wine)] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-60">{pending ? "Saving…" : "Save changes"}</button></div></form>}
      {tab === "Members" && <section className="rounded-2xl border hairline bg-white/55 p-5 sm:p-7"><div className="flex items-center justify-between"><div><h2 className="font-editorial text-2xl">Members</h2><p className="mt-1 text-sm text-[var(--muted)]">Everyone here can add and edit dinners.</p></div><button onClick={() => setInviteOpen(true)} className="focus-ring inline-flex items-center gap-2 rounded-full border hairline px-4 py-2 text-sm font-bold text-[var(--wine)]"><Mail size={15} /> Invite</button></div><div className="mt-5 divide-y hairline">{space.members.map((member) => <div key={member.id} className="flex items-center gap-3 py-4"><span className="grid size-10 place-items-center rounded-full bg-[#d8b69b] text-sm font-bold">{member.name[0]?.toUpperCase()}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold">{member.name}</p><p className="truncate text-xs text-[var(--muted)]">{member.email || "Authenticated member"}</p></div><Pill tone={member.role === "owner" ? "wine" : "neutral"}>{member.role}</Pill></div>)}</div></section>}
      {tab === "Privacy" && <section className="rounded-2xl bg-[#efe3d2] p-5 sm:p-7"><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-white/70"><ShieldCheck size={20} className="text-[var(--olive)]" /></span><div><h2 className="font-editorial text-2xl">Private by default</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Only members of this space can read or change dinners, notes, ratings, and media. Share links are view-only and can be revoked.</p><div className="mt-5 grid gap-3 text-sm"><span className="inline-flex items-center gap-2"><LockKeyhole size={16} /> Member-only database rows</span><span className="inline-flex items-center gap-2"><Users size={16} /> {space.members.length} members</span></div></div></div></section>}
      {tab === "Notifications" && <section className="rounded-2xl border hairline bg-white/55 p-5 sm:p-7"><h2 className="font-editorial text-2xl">Notifications</h2><div className="mt-6 space-y-4"><Toggle label="Dinner reminders" detail="A gentle reminder before a planned dinner." checked={dinnerReminders} onChange={setDinnerReminders} /><Toggle label="Share-link activity" detail="Know when a new read-only link is created." checked={shareAlerts} onChange={setShareAlerts} /></div><p className="mt-6 inline-flex items-center gap-2 text-xs text-[var(--muted)]"><Bell size={14} /> Preferences are saved on this device.</p></section>}
    </div></div>
    {inviteOpen && <div className="fixed inset-0 z-50 grid place-items-end bg-black/45 sm:place-items-center sm:p-5"><form onSubmit={sendInvite} role="dialog" aria-modal="true" className="w-full max-w-md rounded-t-3xl bg-[var(--paper)] p-6 sm:rounded-3xl"><div className="flex items-center justify-between"><h2 className="font-editorial text-3xl">Invite a member</h2><button type="button" onClick={() => { setInviteOpen(false); setInviteLink(""); setCopyState("idle"); }} aria-label="Close" className="focus-ring rounded-full p-2"><X size={19} /></button></div>{inviteLink ? <div className="mt-6"><p className="text-sm text-[var(--muted)]">Send this private invitation link to the intended member.</p><input ref={inviteLinkInput} value={inviteLink} readOnly aria-label="Invitation link" className="field-input mt-4 text-sm" onFocus={(event) => event.currentTarget.select()} /><button type="button" disabled={copyState === "copying"} onClick={copyInviteLink} className="focus-ring mt-3 flex w-full items-center justify-center gap-2 rounded-full bg-[var(--wine)] px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><Copy size={16} /> {copyState === "copying" ? "Copying…" : copyState === "copied" ? "Copied" : "Copy invitation link"}</button>{copyState === "failed" && <p role="alert" className="mt-3 text-sm text-[var(--wine)]">Copy was blocked. Select the link above and press ⌘C.</p>}</div> : <><label className="mt-6 block"><span className="text-sm font-bold">Email address</span><input name="email" type="email" required autoFocus className="field-input mt-2" /></label><button disabled={pending} className="focus-ring mt-6 w-full rounded-full bg-[var(--wine)] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{pending ? "Creating…" : "Create invitation"}</button></>}</form></div>}
  </div>;
}

function Toggle({ label, detail, checked, onChange }: { label: string; detail: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border hairline bg-white/45 p-4"><span><strong className="block text-sm">{label}</strong><small className="mt-1 block text-xs text-[var(--muted)]">{detail}</small></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="size-5 accent-[var(--wine)]" /></label>; }
