"use client";

import { Heart, Sparkles, TrendingUp, Wine } from "lucide-react";
import { useAppData } from "@/components/app-data-provider";
import { PageHeader, Pill } from "@/components/ui";

export function TasteProfile() {
  const { wines, dinners, wineExperiences } = useAppData(); const ratings = dinners.flatMap((dinner) => dinner.ratings); const average = ratings.length ? ratings.reduce((sum, item) => sum + item.rating, 0) / ratings.length : 0;
  const grapeCounts = wines.flatMap((wine) => wine.grapes).reduce<Record<string, number>>((counts, grape) => ({ ...counts, [grape]: (counts[grape] ?? 0) + 1 }), {}); const topGrape = Object.entries(grapeCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "Still discovering";
  const total = Math.max(1, wines.length); const percent = (colors: string[]) => Math.round(wines.filter((wine) => colors.includes(wine.color)).length / total * 100); const tastes = [{ label: "Bright & mineral", value: Math.min(100, 35 + percent(["white", "sparkling"])) }, { label: "Savory & earthy", value: Math.min(100, 30 + percent(["red", "orange"])) }, { label: "Floral & aromatic", value: Math.min(100, 20 + Math.round(wines.filter((wine) => wine.grapes.some((grape) => /riesling|muscat|gew/i.test(grape))).length / total * 100)) }, { label: "Rich & generous", value: Math.min(100, 25 + percent(["red"])) }, { label: "Adventurous", value: Math.min(100, 20 + percent(["orange", "rosé"])) }];
  return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-7 sm:py-9 xl:px-10"><PageHeader eyebrow="Our taste" title="The shape of what you love." description="A living portrait drawn from everyone’s ratings, notes, repeat bottles, and favorite pairings." />
    <div className="mt-8 grid gap-5 lg:grid-cols-[1fr_.8fr]"><section className="rounded-2xl bg-[var(--wine-deep)] p-6 text-white sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e6a38a]">Shared palate</p><h2 className="font-editorial mt-2 text-3xl">A portrait in progress</h2></div><Sparkles className="text-[#e6a38a]" /></div><div className="mt-8 space-y-5">{tastes.map((taste) => <div key={taste.label}><div className="mb-2 flex justify-between text-sm"><span>{taste.label}</span><span className="text-white/55">{taste.value}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#d75539] to-[#efb180]" style={{ width: `${taste.value}%` }} /></div></div>)}</div></section><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1"><Insight icon={Wine} eyebrow="Most collected grape" title={topGrape} copy={`${wines.length} wines in the shared journal.`} /><Insight icon={Heart} eyebrow="Table average" title={average ? `${average.toFixed(1)} / 5` : "No ratings yet"} copy={`${ratings.length} personal ratings across your dinners.`} /></div></div>
    <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--tomato)]">Patterns emerging</p><h2 className="font-editorial mt-2 text-3xl">What the table keeps saying</h2></div><TrendingUp className="text-[var(--olive)]" /></div><div className="mt-5 grid gap-4 md:grid-cols-3"><TasteNote title="Bottles opened" copy={`${wineExperiences.length} distinct wine experiences are shaping this profile.`} tags={["wine history", "live"]} /><TasteNote title="Pairings saved" copy={`${dinners.reduce((sum, dinner) => sum + dinner.pairings.length, 0)} explicit dish-to-wine pairings so far.`} tags={["food", "wine"]} /><TasteNote title="Memories kept" copy={`${dinners.length} dinners across home and restaurant tables.`} tags={["journal", "shared"]} /></div></section>
  </div>;
}

function Insight({ icon: Icon, eyebrow, title, copy }: { icon: typeof Wine; eyebrow: string; title: string; copy: string }) { return <div className="rounded-2xl border hairline bg-white/55 p-5"><span className="grid size-10 place-items-center rounded-full bg-[#efe2d0]"><Icon size={19} className="text-[var(--wine)]" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-[var(--muted)]">{eyebrow}</p><h3 className="font-editorial mt-1 text-3xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{copy}</p></div>; }
function TasteNote({ title, copy, tags }: { title: string; copy: string; tags: string[] }) { return <article className="rounded-2xl border hairline bg-white/50 p-5"><h3 className="font-editorial text-2xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{copy}</p><div className="mt-5 flex flex-wrap gap-2">{tags.map((tag) => <Pill key={tag}>{tag}</Pill>)}</div></article>; }
