"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarDays, Edit3, Grape, MapPin, Wine as WineIcon, X } from "lucide-react";
import { useAppData } from "@/components/app-data-provider";
import { Pill, Rating } from "@/components/ui";
import type { WineColor } from "@/lib/types";

export function WineDetail({ wineId }: { wineId: string }) {
  const data = useAppData(); const wine = data.wines.find((item) => item.id === wineId); const [editing, setEditing] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  if (!data.ready) return <div className="grid min-h-[60vh] place-items-center text-sm text-[var(--muted)]">Opening the bottle notes…</div>;
  if (!wine) return <div className="mx-auto max-w-xl px-5 py-20 text-center"><h1 className="font-editorial text-4xl">Wine not found.</h1><Link href="/wines" className="mt-5 inline-block font-semibold text-[var(--wine)]">Return to the wine journal</Link></div>;
  const experiences = data.wineExperiences.filter((item) => item.wineId === wine.id);
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await data.updateWine(wine.id, { producer: String(form.get("producer")), cuvee: String(form.get("cuvee")), vintage: Number(form.get("vintage")), region: String(form.get("region")), country: String(form.get("country")), grapes: String(form.get("grapes")).split(",").map((item) => item.trim()).filter(Boolean), color: String(form.get("color")) as WineColor }); setEditing(false); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Could not update wine."); } finally { setBusy(false); } };
  const average = experiences.length ? experiences.reduce((sum, item) => sum + item.rating, 0) / experiences.filter((item) => item.rating > 0).length || 0 : 0;
  return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-7 sm:py-9 xl:px-10"><div className="flex items-center justify-between"><Link href="/wines" className="focus-ring inline-flex items-center gap-2 rounded-lg text-sm font-semibold text-[var(--muted)]"><ArrowLeft size={17} /> Wine journal</Link><button onClick={() => setEditing(true)} className="focus-ring inline-flex items-center gap-2 rounded-full border hairline bg-white/55 px-4 py-2 text-sm font-semibold"><Edit3 size={15} /> Edit</button></div>
    <section className="mt-7 grid gap-7 rounded-[1.5rem] bg-[var(--wine-deep)] p-6 text-white sm:p-9 lg:grid-cols-[220px_1fr]"><div className="grid min-h-56 place-items-center rounded-2xl bg-gradient-to-br from-white/12 to-white/[.03]"><div className="relative"><WineIcon size={104} strokeWidth={.8} className="text-[#dba685]" /><span className="absolute -right-4 top-2 rotate-6 rounded bg-[#e8d9c5] px-2 py-1 text-[.6rem] font-bold text-[var(--wine)]">{wine.vintage}</span></div></div><div className="flex flex-col justify-center"><div className="flex flex-wrap gap-2"><Pill tone="wine">{wine.color}</Pill><span className="text-xs uppercase tracking-[.15em] text-white/55">{wine.region} · {wine.country}</span></div><h1 className="font-editorial mt-5 text-5xl leading-[.95] sm:text-6xl">{wine.producer}</h1><p className="mt-2 text-xl text-white/72">{wine.cuvee} · {wine.vintage}</p><div className="mt-7 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/15 pt-6"><div><p className="text-xs uppercase tracking-[.14em] text-white/45">Your average</p><div className="mt-1"><Rating value={average} /></div></div><div><p className="text-xs uppercase tracking-[.14em] text-white/45">Opened</p><p className="mt-1 font-bold">{experiences.length} times</p></div><div><p className="text-xs uppercase tracking-[.14em] text-white/45">Grapes</p><p className="mt-1 font-bold">{wine.grapes.join(", ") || "Not noted"}</p></div></div></div></section>
    <div className="mt-9 grid gap-8 lg:grid-cols-[1fr_280px]"><section><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--tomato)]">Wine experiences</p><h2 className="font-editorial mt-2 text-3xl">The nights you opened it</h2><div className="mt-5 space-y-4">{experiences.map((experience) => { const dinner = data.dinners.find((item) => item.id === experience.dinnerId); if (!dinner) return null; return <Link key={experience.id} href={`/dinners/${dinner.id}`} className="lift focus-ring block rounded-2xl border hairline bg-white/55 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#e9dbc8]"><CalendarDays size={18} className="text-[var(--wine)]" /></span><div><h3 className="font-editorial text-xl">{dinner.title}</h3><p className="mt-1 inline-flex items-center gap-1 text-xs text-[var(--muted)]"><MapPin size={12} /> {dinner.venue}</p></div></div>{experience.rating > 0 && <Rating value={experience.rating} />}</div><p className="mt-4 border-l-2 border-[var(--tomato)] pl-4 text-sm italic leading-6 text-[var(--muted)]">{experience.servingNote || "No serving note yet."}</p></Link>; })}{experiences.length === 0 && <p className="rounded-2xl border border-dashed hairline p-8 text-sm text-[var(--muted)]">This bottle has not been opened at a dinner yet.</p>}</div></section><aside><div className="rounded-2xl border hairline bg-[#efe3d2] p-5"><Grape size={21} className="text-[var(--olive)]" /><h2 className="font-editorial mt-4 text-2xl">What works</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Pairing notes from future dinners will collect here and shape your shared taste profile.</p></div></aside></div>
    {editing && <div className="fixed inset-0 z-50 grid place-items-end bg-black/45 sm:place-items-center sm:p-5"><form onSubmit={save} role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-lg overflow-auto rounded-t-3xl bg-[var(--paper)] p-6 sm:rounded-3xl"><div className="flex items-center justify-between"><h2 className="font-editorial text-3xl">Edit wine</h2><button type="button" onClick={() => setEditing(false)} aria-label="Close" className="focus-ring rounded-full p-2"><X size={19} /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-sm font-bold">Producer</span><input name="producer" required defaultValue={wine.producer} className="field-input mt-2" /></label><label className="sm:col-span-2"><span className="text-sm font-bold">Cuvée</span><input name="cuvee" defaultValue={wine.cuvee} className="field-input mt-2" /></label><label><span className="text-sm font-bold">Vintage</span><input name="vintage" type="number" required defaultValue={wine.vintage} className="field-input mt-2" /></label><label><span className="text-sm font-bold">Color</span><select name="color" defaultValue={wine.color} className="field-input mt-2"><option value="red">Red</option><option value="white">White</option><option value="orange">Orange</option><option value="rosé">Rosé</option><option value="sparkling">Sparkling</option></select></label><label><span className="text-sm font-bold">Region</span><input name="region" defaultValue={wine.region} className="field-input mt-2" /></label><label><span className="text-sm font-bold">Country</span><input name="country" defaultValue={wine.country} className="field-input mt-2" /></label><label className="sm:col-span-2"><span className="text-sm font-bold">Grapes</span><input name="grapes" defaultValue={wine.grapes.join(", ")} className="field-input mt-2" /></label></div>{message && <p role="alert" className="mt-4 text-sm text-[var(--tomato)]">{message}</p>}<button disabled={busy} className="focus-ring mt-6 w-full rounded-full bg-[var(--wine)] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{busy ? "Saving…" : "Save wine"}</button></form></div>}
  </div>;
}
