"use client";

import { useState } from "react";
import { Plus, X } from "lucide-react";
import { PageHeader } from "@/components/ui";
import { WineJournal } from "@/components/wine-journal";
import { useAppData } from "@/components/app-data-provider";
import type { WineColor } from "@/lib/types";

export function WineLibraryPage() {
  const { addWine } = useAppData(); const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [message, setMessage] = useState("");
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget); try { await addWine({ producer: String(form.get("producer")), cuvee: String(form.get("cuvee") ?? ""), vintage: Number(form.get("vintage")), region: String(form.get("region") ?? ""), country: String(form.get("country") ?? ""), grapes: String(form.get("grapes") ?? "").split(",").map((item) => item.trim()).filter(Boolean), color: String(form.get("color")) as WineColor }); setOpen(false); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Could not add wine."); } finally { setPending(false); } };
  return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-7 sm:py-9 xl:px-10"><PageHeader eyebrow="Wine journal" title="Every bottle tells it differently." description="A wine is the bottle. An experience is the night you opened it, who shared it, and what made it sing." action={<button onClick={() => setOpen(true)} className="focus-ring inline-flex items-center justify-center gap-2 rounded-full bg-[var(--wine)] px-5 py-3 text-sm font-bold text-white"><Plus size={17} /> Add wine</button>} /><WineJournal />{open && <div className="fixed inset-0 z-50 grid place-items-end bg-black/45 p-0 sm:place-items-center sm:p-5" role="presentation"><form onSubmit={submit} role="dialog" aria-modal="true" aria-labelledby="add-wine-title" className="max-h-[92vh] w-full max-w-lg overflow-auto rounded-t-3xl bg-[var(--paper)] p-6 shadow-2xl sm:rounded-3xl"><div className="flex items-center justify-between"><h2 id="add-wine-title" className="font-editorial text-3xl">Add a wine</h2><button type="button" onClick={() => setOpen(false)} aria-label="Close" className="focus-ring rounded-full p-2"><X size={19} /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-sm font-bold">Producer</span><input name="producer" required className="field-input mt-2" placeholder="Domaine Tempier" /></label><label className="sm:col-span-2"><span className="text-sm font-bold">Cuvée</span><input name="cuvee" className="field-input mt-2" placeholder="Bandol Rouge" /></label><label><span className="text-sm font-bold">Vintage</span><input name="vintage" type="number" min="1800" max="2200" required defaultValue={new Date().getFullYear()} className="field-input mt-2" /></label><label><span className="text-sm font-bold">Color</span><select name="color" className="field-input mt-2"><option value="red">Red</option><option value="white">White</option><option value="orange">Orange</option><option value="rosé">Rosé</option><option value="sparkling">Sparkling</option></select></label><label><span className="text-sm font-bold">Region</span><input name="region" className="field-input mt-2" /></label><label><span className="text-sm font-bold">Country</span><input name="country" className="field-input mt-2" /></label><label className="sm:col-span-2"><span className="text-sm font-bold">Grapes</span><input name="grapes" className="field-input mt-2" placeholder="Mourvèdre, Grenache" /></label></div>{message && <p role="alert" className="mt-4 text-sm text-[var(--tomato)]">{message}</p>}<button disabled={pending} className="focus-ring mt-6 w-full rounded-full bg-[var(--wine)] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{pending ? "Adding…" : "Add to wine journal"}</button></form></div>}</div>;
}
