import type { Metadata } from "next";
import { Heart, Sparkles, TrendingUp, Wine } from "lucide-react";
import { PageHeader, Pill } from "@/components/ui";

export const metadata: Metadata = { title: "Our taste" };
const tastes = [{ label: "Bright & mineral", value: 88 }, { label: "Savory & earthy", value: 81 }, { label: "Floral & aromatic", value: 67 }, { label: "Rich & generous", value: 54 }, { label: "Sweet", value: 22 }];

export default function TastePage() { return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-7 sm:py-9 xl:px-10"><PageHeader eyebrow="Our taste" title="The shape of what you love." description="A living portrait drawn from everyone’s ratings, notes, repeat bottles, and favorite pairings." />
  <div className="mt-8 grid gap-5 lg:grid-cols-[1fr_.8fr]"><section className="rounded-2xl bg-[var(--wine-deep)] p-6 text-white sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e6a38a]">Shared palate</p><h2 className="font-editorial mt-2 text-3xl">A lean toward freshness</h2></div><Sparkles className="text-[#e6a38a]" /></div><div className="mt-8 space-y-5">{tastes.map((taste) => <div key={taste.label}><div className="mb-2 flex justify-between text-sm"><span>{taste.label}</span><span className="text-white/55">{taste.value}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#d75539] to-[#efb180]" style={{ width: `${taste.value}%` }} /></div></div>)}</div></section>
    <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1"><Insight icon={Wine} eyebrow="Most returned to" title="Riesling" copy="Especially dry, mineral bottles with a little age." /><Insight icon={Heart} eyebrow="Favorite match" title="Seafood + white" copy="4.8 average across six pairings." /></div></div>
  <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--tomato)]">Patterns emerging</p><h2 className="font-editorial mt-2 text-3xl">What the table keeps saying</h2></div><TrendingUp className="text-[var(--olive)]" /></div><div className="mt-5 grid gap-4 md:grid-cols-3"><TasteNote title="Serve it warmer" copy="Your notes improve when structured whites sit out 15–20 minutes." tags={["white wine", "temperature"]} /><TasteNote title="Acid wins the table" copy="The group rates high-acid wines 0.7 points above the average." tags={["fresh", "food-friendly"]} /><TasteNote title="Maya loves orange" copy="Her top three recent wine ratings were all skin-contact bottles." tags={["Maya", "orange wine"]} /></div></section>
  </div>; }

function Insight({ icon: Icon, eyebrow, title, copy }: { icon: typeof Wine; eyebrow: string; title: string; copy: string }) { return <div className="rounded-2xl border hairline bg-white/55 p-5"><span className="grid size-10 place-items-center rounded-full bg-[#efe2d0]"><Icon size={19} className="text-[var(--wine)]" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-[var(--muted)]">{eyebrow}</p><h3 className="font-editorial mt-1 text-3xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{copy}</p></div>; }
function TasteNote({ title, copy, tags }: { title: string; copy: string; tags: string[] }) { return <article className="rounded-2xl border hairline bg-white/50 p-5"><h3 className="font-editorial text-2xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{copy}</p><div className="mt-5 flex flex-wrap gap-2">{tags.map((tag) => <Pill key={tag}>{tag}</Pill>)}</div></article>; }
