import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, CalendarDays, Edit3, Grape, MapPin, Wine as WineIcon } from "lucide-react";
import { getDinner, getWine, wineExperiences } from "@/lib/mock-data";
import { Pill, Rating } from "@/components/ui";

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const { id } = await params; return { title: getWine(id).producer }; }
export default async function WineDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const wine = getWine(id); const experiences = wineExperiences.filter((item) => item.wineId === wine.id); const shown = experiences.length ? experiences : wineExperiences.slice(0, 2);
  return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-7 sm:py-9 xl:px-10"><div className="flex items-center justify-between"><Link href="/wines" className="focus-ring inline-flex items-center gap-2 rounded-lg text-sm font-semibold text-[var(--muted)]"><ArrowLeft size={17} /> Wine journal</Link><button className="focus-ring inline-flex items-center gap-2 rounded-full border hairline bg-white/55 px-4 py-2 text-sm font-semibold"><Edit3 size={15} /> Edit</button></div>
    <section className="mt-7 grid gap-7 rounded-[1.5rem] bg-[var(--wine-deep)] p-6 text-white sm:p-9 lg:grid-cols-[220px_1fr]"><div className="grid min-h-56 place-items-center rounded-2xl bg-gradient-to-br from-white/12 to-white/[.03]"><div className="relative"><WineIcon size={104} strokeWidth={.8} className="text-[#dba685]" /><span className="absolute -right-4 top-2 rotate-6 rounded bg-[#e8d9c5] px-2 py-1 text-[.6rem] font-bold text-[var(--wine)]">{wine.vintage}</span></div></div><div className="flex flex-col justify-center"><div className="flex flex-wrap gap-2"><Pill tone="wine">{wine.color}</Pill><span className="text-xs uppercase tracking-[.15em] text-white/55">{wine.region} · {wine.country}</span></div><h1 className="font-editorial mt-5 text-5xl leading-[.95] sm:text-6xl">{wine.producer}</h1><p className="mt-2 text-xl text-white/72">{wine.cuvee} · {wine.vintage}</p><div className="mt-7 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/15 pt-6"><div><p className="text-xs uppercase tracking-[.14em] text-white/45">Your average</p><div className="mt-1"><Rating value={4.8} /></div></div><div><p className="text-xs uppercase tracking-[.14em] text-white/45">Opened</p><p className="mt-1 font-bold">{wine.bottlesOpened} times</p></div><div><p className="text-xs uppercase tracking-[.14em] text-white/45">Grapes</p><p className="mt-1 font-bold">{wine.grapes.join(", ")}</p></div></div></div></section>

    <div className="mt-9 grid gap-8 lg:grid-cols-[1fr_280px]"><section><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--tomato)]">Wine experiences</p><h2 className="font-editorial mt-2 text-3xl">The nights you opened it</h2><div className="mt-5 space-y-4">{shown.map((experience) => { const dinner = getDinner(experience.dinnerId); return <Link key={experience.id} href={`/dinners/${dinner.id}`} className="lift focus-ring block rounded-2xl border hairline bg-white/55 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#e9dbc8]"><CalendarDays size={18} className="text-[var(--wine)]" /></span><div><h3 className="font-editorial text-xl">{dinner.title}</h3><p className="mt-1 inline-flex items-center gap-1 text-xs text-[var(--muted)]"><MapPin size={12} /> {dinner.venue}</p></div></div><Rating value={experience.rating} /></div><p className="mt-4 border-l-2 border-[var(--tomato)] pl-4 text-sm italic leading-6 text-[var(--muted)]">{experience.servingNote}</p></Link>; })}</div></section>
      <aside><div className="rounded-2xl border hairline bg-[#efe3d2] p-5"><Grape size={21} className="text-[var(--olive)]" /><h2 className="font-editorial mt-4 text-2xl">What works</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Savory, slow-cooked dishes. Best after an hour of air. Your highest pairing notes mention roast chicken and herbs.</p><div className="mt-5 flex flex-wrap gap-2"><Pill>roast chicken</Pill><Pill>earthy</Pill><Pill>slow dinner</Pill></div></div></aside>
    </div></div>;
}
